package com.kanvalkalra.colormemory.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig highScoreUserDaoConfig;

    private final HighScoreUserDao highScoreUserDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        highScoreUserDaoConfig = daoConfigMap.get(HighScoreUserDao.class).clone();
        highScoreUserDaoConfig.initIdentityScope(type);

        highScoreUserDao = new HighScoreUserDao(highScoreUserDaoConfig, this);

        registerDao(HighScoreUser.class, highScoreUserDao);
    }

    public void clear() {
        highScoreUserDaoConfig.getIdentityScope().clear();
    }

    public HighScoreUserDao getHighScoreUserDao() {
        return highScoreUserDao;
    }

}
