package com.kanvalkalra.colormemory.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "HIGH_SCORE_USER".
 */
public class HighScoreUser {

    /**
     * Not-null value.
     */
    private String name;
    private long score;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public HighScoreUser() {
    }

    public HighScoreUser(String name, long score) {
        this.name = name;
        this.score = score;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public long getScore() {
        return score;
    }

    public void setScore(long score) {
        this.score = score;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
