package com.kanvalkalra.colormemory.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "HIGH_SCORE_USER".
 */
public class HighScoreUserDao extends AbstractDao<HighScoreUser, Void> {

    public static final String TABLENAME = "HIGH_SCORE_USER";

    /**
     * Properties of entity HighScoreUser.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Name = new Property(0, String.class, "name", false, "NAME");
        public final static Property Score = new Property(1, long.class, "score", false, "SCORE");
    }

    ;


    public HighScoreUserDao(DaoConfig config) {
        super(config);
    }

    public HighScoreUserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HIGH_SCORE_USER\" (" + //
                "\"NAME\" TEXT NOT NULL ," + // 0: name
                "\"SCORE\" INTEGER NOT NULL );"); // 1: score
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HIGH_SCORE_USER\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, HighScoreUser entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getName());
        stmt.bindLong(2, entity.getScore());
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }

    /** @inheritdoc */
    @Override
    public HighScoreUser readEntity(Cursor cursor, int offset) {
        HighScoreUser entity = new HighScoreUser( //
                cursor.getString(offset + 0), // name
                cursor.getLong(offset + 1) // score
        );
        return entity;
    }

    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, HighScoreUser entity, int offset) {
        entity.setName(cursor.getString(offset + 0));
        entity.setScore(cursor.getLong(offset + 1));
    }

    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(HighScoreUser entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }

    /** @inheritdoc */
    @Override
    public Void getKey(HighScoreUser entity) {
        return null;
    }

    /**
     * @inheritdoc
     */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
